### ISSUE TITLE
VeloViewer refresh activities broken

### ISSUE THREAD

**Issue by enqueue** [marcin-gryszkalis/veloviewer-explorer-overlay#2]
## Summary

Refreshing the activities on vv.fork.pl does not seem to work for my VeloViewer account

## Steps to reproduce

1. Go to https://vv.fork.pl/index.php
2. Enter valid athlete ID with settings according to instructions
3. Click on "Refresh Explorer Stats"

## Expected behavior

Great success and beautiful VeloViewer tiles available for B(ike)Router use.

## Actual behavior

Error message: `ERROR: can't find explorer url (activities)`

## Suspicion

I suspect the regular expression not matching the explorer URL in [line 116 of refresh_vv.php](https://github.com/marcin-gryszkalis/veloviewer-explorer-overlay/blob/7fbae4095f28f1305ba19baefbd649a93ed57c2c/refresh_vv.php#L116). It expects a digit following the `explorer` String. However, looking at the network inspector, the URL I see for `explorerSrc` does not include trailing digits before the `.js` suffix:

```js
explorerSrc= "https://s3.veloviewer.com/athletes2/7/5/621764/8549de2e1876afc00bde88109ec87824explorer.js";
```

Perhaps it would be more robust to grep for `explorerSrc`, but you could also make the dot and the digits following "explorer" optional.

**Comment by marcin-gryszkalis** [comment]
Somehow I missed this report, sorry :( fortunately someone else pointed out the same problem.
It was just fixed https://github.com/marcin-gryszkalis/veloviewer-explorer-overlay/commit/a6227b2763563cfd975d2b1d0a360fe21fcfe0c4

Actually it was not about regexp but some internal logic of vv caused it not to publish so called "definite set" of visited squares. Nevertheless - I just added few if-s to skip it when it's not available and it seems to be working properly.
